config/routes.rb
Rails.application.routes.draw do


  resources :articles do
    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :infos

  root 'static_pages#home'
  get  'contact' => 'static_pages#contact'

  devise_for :users
  resources  :users

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :require_admin,   only: [:new, :edit, :create, :update, :destroy]
  before_action :current_info,    only: [:edit, :update, :destroy]

  def index
    @infos = Info.all.order('created_at DESC')
  end

  def new
    @info = Info.new
  end

  def edit
    @info = Info.find(params[:id])
  end

  def create
    @info = Info.new(info_params)
    if @info.save
      flash[:success] = t(:info_created)
      redirect_to infos_url
    else
      render "new"
    end
  end

  def update
    if @info.update_attributes(info_params)
      flash[:success] = t(:info_updated)
      redirect_to infos_url
    else
      render "edit"
    end
  end

  def destroy
    @info.destroy
    flash[:success] = t(:info_deleted)
    redirect_to infos_url
  end

  private

    def info_params
      params.require(:info).permit(:title, :text)
    end

    def current_info
      @info = Info.find(params[:id])
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @info.errors.any? %>
        <div class="alert-error alert">
          <p>
            <%= t(:errors) %>(<%= @info.errors.count %>)
          </p>
          <ul>
            <% @info.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= form_for @info,
                 html: {class: "new-info-form"} do |f| %>
        <p>
          <%= f.label :text, class: "sr-only" %>
          <%= f.text_area :text, class: "form-control comment-text-area", rows: "3",
                          placeholder: t(:p_info) %>
        </p>
        <p>
          <%= f.submit t(:add), class: "btn btn-primary" %>
        </p>
    <% end %>
  </div>
</div>

app/views/infos/_info.html.erb
<div class="row comment">
  <div class="col-md-12">
    <div class="col-md-9">
      <div class="info-info">
        <p>
          <%= info.created_at %>
          <% if info.created_at != info.updated_at %>
              , <%= t(:last_update) %>: <%= info.updated_at %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="col-md-12">
      <%= info.text %>
    </div>
    <% if current_user.try(:admin) %>
        <div class="btn-group col-md-3 comment-edit-delete" >
          <%= link_to t(:edit), edit_info_path(info.id),
                      class: "btn btn-primary btn-sm btn-info edit-info" %>
          <%= link_to t(:delete), info,
                      class: "btn btn-primary btn-sm btn-info",
                      method: :delete,
                      data: { confirm: t(:you_sure) } %>
        </div>
    <% end %>
  </div>
</div>
<hr>

app/views/infos/edit.html.erb
<% provide(:title, t(:edit_info)) %>
<div class="row">
  <div class="col-md-12">
    <h2><%= t(:edit_info) %></h2>
    <%= form_for @info, html: {class: "edit-info-form"} do |f| %>
        <p>
          <%= f.label t(:text), class: "sr-only" %>
          <%= f.text_area :text, class: "form-control", rows: "10" %>
        </p>
        <p>
          <%= f.submit t(:update), class: "btn btn-primary" %>
        </p>
    <% end %>
  </div>
</div>

app/views/infos/index.html.erb
<% provide(:title, t(:infos)) %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="infos-list">
      <h1>
        <% if current_user.try(:admin?) %>
            <%= link_to t(:new_info), new_info_path, class: "new-info-link btn btn-primary" %>
        <% end %>
      </h1>
      <%= render @infos %>
      </div>
  </div>
</div>

app/views/infos/new.html.erb
<% provide(:title, t(:new_info)) %>
<div class="row">
  <div class="col-md-12">
    <% if @info.errors.any? %>
        <div class="alert-error alert">
          <p>
            <%= t(:errors) %> (<%= @info.errors.count %>):
          </p>
          <ul>
            <% @info.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <h2><%= t(:new_info) %></h2>
    <%= render "form" %>
  </div>
</div>