config/routes.rb
Rails.application.routes.draw do


  resources :articles do
    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :infos

  root 'static_pages#home'
  get  'contact' => 'static_pages#contact'

  devise_for :users
  resources  :users

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'The Blog', root_path, class: 'navbar-brand site-name nav-link' %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to t(:home), root_path, class: 'nav-link home-link' %></li>
          <li><%= link_to t(:infos), infos_path, class: 'nav-link infos-link' %></li>
          <li><%= link_to t(:articles), articles_path, class: 'nav-link articles-link' %></li>
          <% if current_user.try(:admin) %>
            <li><%= link_to t(:users), users_path, class: 'nav-link users-link' %></li>
          <% end %>
          <li><%= link_to t(:contact), contact_path, class: 'nav-link contact-link' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li>
                <%= link_to ('<i class="glyphicon glyphicon-user"></i> ' + t(:my_account) ).html_safe,
                            user_path(current_user.id),
                            class: 'nav-link my-account-link' %>
              </li>
              <li>
                <%= link_to ('<i class="glyphicon glyphicon-log-out"></i> ' + t(:logout)).html_safe,
                            destroy_user_session_path, :method=>'delete',
                            class: 'nav-link logout-link' %>
              </li>
          <% else %>
              <li>
                <%= link_to ('<i class="glyphicon glyphicon-user"></i> ' + t(:create_account)).html_safe,
                            new_user_registration_path,
                            class: 'nav-link create-account-link' %>
              </li>
              <li>
                <%= link_to ('<i class="glyphicon glyphicon-log-in"></i> ' + t(:login)).html_safe,
                            new_user_session_path,
                            class: 'nav-link login-link' %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>